# Generated by Django 5.2.6 on 2025-11-25 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0004_alter_jobcategory_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('application', 'New Application'), ('expiry', 'Job Expiry'), ('custom', 'Custom Alert'), ('system', 'System Alert')], default='custom', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_alerts', to='hiring.businessprofile')),
                ('job_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_alerts', to='hiring.joblisting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('in_app_notifications', models.BooleanField(default=True)),
                ('new_applications', models.BooleanField(default=True)),
                ('job_expiry_alerts', models.BooleanField(default=True)),
                ('candidate_updates', models.BooleanField(default=True)),
                ('system_maintenance', models.BooleanField(default=False)),
                ('marketing_emails', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='hiring.businessprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessSentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('application', 'Application Update'), ('job', 'Job Update'), ('system', 'System Notification'), ('marketing', 'Marketing')], default='system', max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='hiring.businessprofile')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
