# Generated by Django 5.2.6 on 2025-11-26 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0005_businessalert_businessnotificationpreference_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name_plural': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='employmenthistory',
            options={'verbose_name_plural': 'Employment Histories'},
        ),
        migrations.AddField(
            model_name='skill',
            name='is_business_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='recommended_by_business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_skills', to='hiring.businessprofile'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='current_home_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='current_salary',
            field=models.CharField(blank=True, choices=[('0_50k', '0 - 50K Annually'), ('50_100k', '50 - 100K Annually'), ('100_150k', '100 - 150K Annually'), ('150_200k', '150 - 200K Annually'), ('200k_plus', '200K+ Annually')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='desired_salary',
            field=models.CharField(blank=True, choices=[('0_50k', '0 - 50K Annually'), ('50_100k', '50 - 100K Annually'), ('100_150k', '100 - 150K Annually'), ('150_200k', '150 - 200K Annually'), ('200k_plus', '200K+ Annually')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('african', 'African'), ('coloured', 'Coloured'), ('indian', 'Indian'), ('white', 'White'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='is_citizen',
            field=models.CharField(blank=True, choices=[('south_african', 'South African Citizen'), ('permanent_resident', 'Permanent Resident'), ('work_permit', 'Work Permit'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='preferred_job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='title',
            field=models.CharField(blank=True, choices=[('mr', 'Mr'), ('ms', 'Ms'), ('mrs', 'Mrs'), ('dr', 'Dr')], max_length=10, null=True),
        ),
    ]
