# Generated by Django 5.2.6 on 2025-11-26 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0006_alter_education_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='hiring.applicantprofile'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='recommended_by_business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_skills', to='hiring.businessprofile'),
        ),
    ]
