# Generated by Django 5.2.6 on 2025-11-26 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0007_alter_skill_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessEmploymentPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_contract_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], max_length=20)),
                ('positions_available', models.PositiveIntegerField(default=1)),
                ('job_title_keywords', models.JSONField(blank=True, default=list)),
                ('required_experience_years', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_preferences', to='hiring.businessprofile')),
            ],
            options={
                'verbose_name_plural': 'Business Employment Preferences',
            },
        ),
    ]
