# Generated by Django 5.2.6 on 2025-11-26 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0008_businessemploymentpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_type', models.CharField(choices=[('education', 'Education'), ('skills', 'Skills'), ('employment', 'Employment'), ('experience', 'Experience'), ('certifications', 'Certifications'), ('languages', 'Languages'), ('location', 'Location'), ('industry', 'Industry'), ('custom', 'Custom')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('criteria', models.JSONField(blank=True, default=dict)),
                ('positions_available', models.PositiveIntegerField(default=1)),
                ('priority_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='hiring.businessprofile')),
            ],
            options={
                'ordering': ['-priority_level', '-created_at'],
            },
        ),
    ]
