# Generated by Django 5.2.6 on 2025-12-01 08:03

import hiring.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0011_post_comment_postview_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='shares',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public - Everyone'), ('connections', 'Connections Only'), ('company', 'Company Only'), ('private', 'Private - Just Me')], default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/images/%Y/%m/%d/', validators=[hiring.validators.validate_file_size, hiring.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('job', 'Job Post'), ('update', 'Company Update'), ('news', 'Industry News'), ('general', 'General Post'), ('question', 'Question'), ('achievement', 'Achievement'), ('advice', 'Career Advice')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='posts/videos/%Y/%m/%d/', validators=[hiring.validators.validate_file_size, hiring.validators.validate_video_file_extension]),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='hiring_post_created_89f18f_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['post_type'], name='hiring_post_post_ty_58ac49_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author'], name='hiring_post_author__80707f_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_published'], name='hiring_post_is_publ_65f4e0_idx'),
        ),
    ]
