# Generated by Django 5.2.6 on 2025-12-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0014_post_comment_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='company_name',
            field=models.CharField(default='Admin', max_length=200),
        ),
    ]
